#+BLOG: myblog
#+POSTID: 
#+ORG2BLOG:
#+DATE: <2021-05-10 Mon>
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: rl
#+TAGS: Electric vehicles, Reinforcement Learning
#+DESCRIPTION: 
#+TITLE: Range anxiety relief for electric vehicles
* tl;dr
** The problem
   + Range anxiety forms a roadblock against widespread adoption of EVs [[https://www.sciencedirect.com/science/article/pii/S0301421512005162]]
   + Radical changes in battery performance seem unlikely given relatively slow rate of progress so far [[https://www.researchgate.net/publication/255748960_Thermodynamic_analysis_on_energy_densities_of_batteries]] although batteries are getting cheaper https://theconversation.com/battery-costs-drop-even-faster-as-electric-car-sales-continue-to-rise-39780
   + Fuel cells (e.g., storing hydrogen under pressure and converting to electricity) are an option but have their own problems https://www.zdnet.com/article/the-problem-with-fuel-cells/ https://futureofworking.com/10-advantages-and-disadvantages-of-hydrogen-fuel-cells/
   + Many journeys are quite short but occasionally long journeys must be undertaken https://www.sciencedirect.com/science/article/pii/S0968090X1100012X
   + Availability of charging points in UK is behind many other countries [[https://www.edie.net/news/8/UK--lags-behind--mainland-Europe-on-EV-infrastructure/]]
   + On the one hand, we must address excess energy consumption, such as the climate control system:
     + Natural ventilation is poorly used by current approaches
     + Heating systems within the car are dealt with on a component level and not fully integrated
     + Modern human thermal comfort models aren't taken into account
   + On the other hand, better and more accurate range information systems are needed
     + Current approaches do not adequately incorporate contextual information and can be overly optimistic on long drives
** The vision
   + The design of EV thermal systems can be optimised to better make use of:
     + available opportunities (such as, including more natural ventilation when the cabin is hot and the ambient air is cool);
     + integrated control of hot air and radiant surfaces to achieve comfort with minimal effort;
     + advanced technologies (insulation, targeted vents, radiant panels, heat pumps) to reduce the energy cost of comfort.
   + More accurate EV drive range prediction via better contextual information, including:
     + Acceleration profile
     + Speed
     + Hilly versus flat terrain
     + Time of day
     + Weather
** The outcomes
+ At the small scale, reducing the energy cost of providing comfort in EVs will help reduce range anxiety and contribute to uptake of EVs.
+ On a larger scale, each percentage point improvement in the energy efficiency of EV comfort systems will help towards reducing the our overall energy footprint. 

* Optimising the climate system
** Better human thermal comfort models

 + The study of human thermal comfort has evolved considerably since early models were proposed by Fanger in the 1970s.
 + Such traditional models focus on minimising the percent of the population that would be dissatisfied by a particular set of environmental conditions, mainly based on temperature but also including factors such as clothing, radiant heat, humidity and so forth.
 + Air conditioning systems in buildings and vehicles traditionally aimed to bring the temperature to a target value, such as 21 deg. C.
 + However, it has since been realised that humans tend to adapt to their surroundings and will be comfortable in much hotter temperatures when living in a hot climate, for example.
 + Since around 1998, adaptive models of thermal comfort that incorporate recent environmental experience have gained popularity.
 + These new models paved the way to reducing the energy cost of air conditioning buildings and could potentially do the same for vehicle climate systems.

** Example: natural ventilation

 + One way to improve the energy performance of buildings is to make better use of natural ventilation.
 + Rather than strictly conditioning temperatures to 21C, a naturally ventilated building promotes airflow through a building to encourage heat loss. Ventilation systems only close when the outside temperature becomes too high (or too cold).
 + An immediate objection to making use of natural ventilation in cars is that car users don't want their window opened automatically.
   + However, encouraging users to wind down windows when beneficial (e.g., hot inside but cool outside) will in most cases be sufficient.
   + Furthermore, the control system can change how it behaves when the windows are open.
   + Automated natural ventilation doesn't just have to be through windows - vents can receive air from outside too without needing to take that air through the complicated cooling and heating cycle normally performed.

* Range prediction tools and driver information
+ Tools for predicting the remaining range of the vehicle are already commonplace.
+ However, such tools are inaccurate and in some key situations, such as longer drives, catastrophically optimistic.
+ Such optimism derives from a simple view on the range calculation: recent driving performance (miles per kWh) is used as the main and perhaps only factor.
+ However, recent drives are likely to be shorter, around-town, drives that are at lower speeds and thus more energy efficient.
+ Motorway driving, on the other hand, where the range calculation becomes crucial, may yield quite different range performance due to wind resistance becoming the dominating factor.

* What it takes to get there

  + For the problem of estimating range, the domain of Reinforcement Learning suggests a neat solution: just as the core part of Alpha-Zero can accurately guess the winner of a game of chess from the current position, the same approach can be used to estimate the remaining drive range depending on the best available contextual information.
  + At the same time, RL may also be able to help with developing an optimised climate system that keeps you comfortable and the windshield defogged at the least energy cost.
  + The key to both of these solutions lies not in clever algorithms but rather in gathering experience.

** Real world experience leading to fast simulation
+ How does the air temperature in the car change when you run the heater at power A, the compressor at speed B, the recirculation flap set to position C, and the air vent distribution set to D? Clearly, this doesn't just depend on these settings but also: the current cabin air temperature(s), the external air temperature, the humidity inside and out, the incident solar radiation, the heat stored in the chassis of the car, and so forth. 
+ One approach to this problem is to model the physics of the situation, which has the advantage that the resulting model can be interpreted and that a change to the physical environment can be incorporated by a small change to the model.
+ However, such models are difficult to build correctly and complex to compute once built meaning that any simulation may be about as slow as real-time.
+ Furthermore, it is difficult to accurately simulate detail within the cabin (such as, the temperature at the driver's head versus at their foot) without resorting to computational fluid dynamics (CFD), which then is much slower to compute.
+ Experience data is often gathered in Climatic Wind Tunnels (CWTs). The advantage of using a CWT is that the experiment can be readily reproduced. The disadvantage is that the experience gathered this way is not necessarily realistic.
  + The lack of realism is emphasised by the Dieselgate scandal where `cheat' mechanisms used by vendors made the laboratory emissions tests appear to show low levels of emissions whereas the actual emissions when tested on the road were much higher.
+ Vehicle manufacturers could potentially gather in-use experience with agreement from end-users and thus build a richer experience set.

** Build fast simulation from experience or learn directly?
 + It is an open question how best to make use of experience data for Reinforcement Learning but two obvious options are available.
   + The first is to learn a simulator from experience. Simulators learnt this way are likely to be much faster in execution that traditional, physics based approaches.
   + The second option is to use RL directly from experience. The main difficulty with this (explored by the Dagger algorithm) is a mismatch in probability distributions between the policy used during experience occurring and the policy that you are trying to learn.
 + When using the first approach, it is necessary to protect against the RL policy learning to exploit inadequacies in the simulator. For example, the policy might drive the state to part of the state space that was not experienced and for which the simulator responds poorly. 

** What it really takes is courage
+ Even within the confines of a research project, engineers are reluctant to use machine learning to control a real system, even one so constrained and low-risk as the climate system or the range estimator.
+ The car industry is quite conservative---it takes a long time for radical ideas to be adopted.
+ On the other hand, /sometimes/ we are brave.
